# -*- coding: utf-8 -*-
"""extract_tables_pdf

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Df-Wpu-YlyKrxhwzs6I70wf9JNxN4fE8
"""

!pip install pdfplumber
import pdfplumber
import pandas as pd
import os

def extract_tables_from_pdf(pdf_path, output_dir):
    """
    Extract tables from a given PDF and save them as separate Excel files.
    :param pdf_path: Path to the input PDF file.
    :param output_dir: Directory to save the extracted Excel files.
    """
    # Create output directory if not exists
    os.makedirs(output_dir, exist_ok=True)

    with pdfplumber.open(pdf_path) as pdf:
        table_count = 0

        for page_number, page in enumerate(pdf.pages, start=1):
            tables = page.extract_tables()

            for table in tables:
                df = pd.DataFrame(table)
                df.to_excel(os.path.join(output_dir, f"table_{table_count + 1}.xlsx"), index=False, header=False)
                table_count += 1

    print(f"{table_count} tables extracted and saved in '{output_dir}'.")

if __name__ == "__main__":
    from google.colab import files

    pdf_path = "stock_market_dataset.pdf"  # Change this to your uploaded PDF file
    output_dir = "extracted_tables"
    extract_tables_from_pdf(pdf_path, output_dir)

    # Download extracted files
    for file in os.listdir(output_dir):
        files.download(os.path.join(output_dir, file))





